name: dccm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  bloc: ^8.1.4
  flutter_spinkit: ^5.2.1
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
     - images/launchscreen.png
     - images/Registerscreen.png
     - assets/
     



  
 